# ENVIRONMENTS
os:
  - linux
  - osx
osx_image: xcode9.2
sudo: false
filter_secrets: false
# INSTALLATION
addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - libstdc++6
      - fonts-droid
language: node_js
node_js:
  - "6"
git:
  # We rely on git tags for determining the version.
  depth: false
cache:
  bundler: true
  directories:
    - $HOME/.pub-cache
install:
  - ./dev/travis_install.sh

before_install:
  - chmod +x ./dev/*.sh

# TESTING
before_script:
  - ./dev/travis_setup.sh
script:
  - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
  - ./dev/travis_script.sh
